CREATE TABLE submission_journals(preview_id TEXT PRIMARY KEY,project_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,plan_hash TEXT NOT NULL,payload_hash TEXT NOT NULL,draft_json TEXT NOT NULL,draft_hash TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('prepared','committed','acknowledged','abandoned')),task_id TEXT REFERENCES tasks(id),CHECK((state IN ('prepared','abandoned') AND task_id IS NULL) OR (state IN ('committed','acknowledged') AND task_id IS NOT NULL)));
CREATE UNIQUE INDEX one_pending_submission_per_project ON submission_journals(project_id) WHERE state IN ('prepared','committed');
CREATE TRIGGER immutable_submission_draft BEFORE UPDATE ON submission_journals WHEN NEW.preview_id!=OLD.preview_id OR NEW.project_id!=OLD.project_id OR NEW.idempotency_key!=OLD.idempotency_key OR NEW.plan_hash!=OLD.plan_hash OR NEW.payload_hash!=OLD.payload_hash OR NEW.draft_json!=OLD.draft_json OR NEW.draft_hash!=OLD.draft_hash BEGIN SELECT RAISE(ABORT,'immutable submission draft'); END;
CREATE TRIGGER submission_journal_transition BEFORE UPDATE ON submission_journals WHEN NOT ((OLD.state='prepared' AND NEW.state='committed') OR (OLD.state='prepared' AND NEW.state='abandoned') OR (OLD.state='committed' AND NEW.state='acknowledged' AND NEW.task_id=OLD.task_id)) BEGIN SELECT RAISE(ABORT,'invalid submission journal transition'); END;
CREATE TRIGGER validate_journal_task_insert BEFORE INSERT ON submission_journals WHEN NEW.task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM task_submissions s WHERE s.preview_id=NEW.preview_id AND s.project_id=NEW.project_id AND s.idempotency_key=NEW.idempotency_key AND s.plan_hash=NEW.plan_hash AND s.payload_hash=NEW.payload_hash AND s.task_id=NEW.task_id) BEGIN SELECT RAISE(ABORT,'journal task receipt mismatch'); END;
CREATE TRIGGER validate_journal_task_update BEFORE UPDATE ON submission_journals WHEN NEW.task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM task_submissions s WHERE s.preview_id=NEW.preview_id AND s.project_id=NEW.project_id AND s.idempotency_key=NEW.idempotency_key AND s.plan_hash=NEW.plan_hash AND s.payload_hash=NEW.payload_hash AND s.task_id=NEW.task_id) BEGIN SELECT RAISE(ABORT,'journal task receipt mismatch'); END;
CREATE TRIGGER preserve_submission_journals BEFORE DELETE ON submission_journals BEGIN SELECT RAISE(ABORT,'preserve submission journal'); END;
CREATE TRIGGER reject_abandoned_submission BEFORE INSERT ON task_submissions WHEN EXISTS(SELECT 1 FROM submission_journals WHERE preview_id=NEW.preview_id AND state='abandoned') BEGIN SELECT RAISE(ABORT,'abandoned submission'); END;
PRAGMA user_version=7;
